# Generated by Django 5.0.6 on 2024-05-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='url_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('links', models.TextField()),
                ('status', models.TextField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScraperAPI.request_details', to_field='request_id')),
            ],
        ),
    ]
