# Generated by Django 5.0.6 on 2024-05-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperAPI', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='url_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ids', models.CharField(max_length=300, unique=True)),
                ('urls', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('links', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
