# Generated by Django 5.0.6 on 2024-05-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScraperAPI', '0006_url_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_details',
            name='request_ids',
            field=models.CharField(max_length=300),
        ),
    ]
